### ISSUE TITLE
Health Route Giving 503 on Production

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP-Server#275] opened 2023-07-13 01:26 UTC
It looks like the health route on production is returning a 503.  It does return a partial body:
```
{
  "serverVersion": "v1.1.0.29-1",
  "details": [
    {
      "key": "testSessionProcessing",
      "description": "The TestSession internal processing load status.",
      "data": {
        "healthStatusDefinitions": {
          "Healthy": "Oldest pending TestSession is < 1 hours old.",
          "Degraded": "Oldest pending TestSession is > 1 hours old.",
          "Unhealthy": "Oldest pending TestSession is > 4 hours old."
        }
      }
    }
  ]
}
```

But the `status` key is missing

Demo seems to be OK:
```
{
  "status": "Healthy",
  "serverVersion": "v1.1.0.29-1",
  "details": [
    {
      "key": "testSessionProcessing",
      "status": "Healthy",
      "description": "The TestSession internal processing load status.",
      "data": {
        "healthStatusDefinitions": {
          "Healthy": "Oldest pending TestSession is < 1 hours old.",
          "Degraded": "Oldest pending TestSession is > 1 hours old.",
          "Unhealthy": "Oldest pending TestSession is > 4 hours old."
        }
      }
    }
  ]
}
```

**Comment by livebe01** [comment] 2023-07-13 12:40
Hi @AlexThurston, this seems to be an artifact of something going wonky on our backend (see https://github.com/usnistgov/ACVP-Server/issues/270). Thanks for reporting this. We should have this resolved shortly.

**Comment by AlexThurston** [comment] 2023-07-13 12:41
Great.  Thanks for the update.  It had been working for the past couple of days and just start yesterday afternoon for me again.  Production was also reporting degraded at the time so I wondered if they were related.

**Comment by livebe01** [comment] 2023-07-13 13:23
Everything should be back online and fully functioning now. Thanks again.

**Comment by AlexThurston** [comment] 2023-07-13 13:28
Seems like it's still giving a 503 from production

```
unexpected status code 503 != 200: {
                   "serverVersion": "v1.1.0.29-1",
                   "details": [
                     {
                       "key": "testSessionProcessing",
                       "description": "The TestSession internal processing load status.",
                       "data": {
                         "healthStatusDefinitions": {
                           "Healthy": "Oldest pending TestSession is < 1 hours old.",
                           "Degraded": "Oldest pending TestSession is > 1 hours old.",
                           "Unhealthy": "Oldest pending TestSession is > 4 hours old."
                         }
                       }
                     }
                   ]
                 }
```

**Comment by AlexThurston** [comment] 2023-07-13 13:29
Bahahah!  Nevermind.  I just tried it again and it's working.

**Comment by jbrock24** [comment] 2023-07-18 13:13
Prod just got restarted, about 30m ago, let me know if that

**Comment by AlexThurston** [comment] 2023-07-18 13:20
Still the same behaviour.  503s.  The response does still have the body, but it's missing the status key.

Not sure if it's related, or a different thing, but demo is reporting degraded as well.  However, the call is succeeding with a 200 in that case.

**Comment by jbrock24** [comment] 2023-07-18 14:13
Sorry about the issues! Demo is currently under load from a bunch of LMS submissions, hopefully that will be cleared up soon. The issue with Prod is being looked into.

**Comment by jbrock24** [comment] 2023-07-18 16:41
So, it appears we don't have enough LMS Pool values stored, we're currently looking into ways to better handle this. Thanks for the feedback!

**Comment by jarnold01** [comment] 2023-07-18 18:18
The processing issues have been resolved in both the Demo and Prod environments, though the root causes were different, along with some unfortunate timing. So everything should be operating normally again. Appreciate you commenting with your observations as well @AlexThurston ; thanks.

**Closed by jarnold01** 2023-07-18 18:18 UTC

**Comment by AlexThurston** [comment] 2023-10-12 13:08
This appears to be happening again on Production.  503s from the health route.  Prod still seems to be responding to other actions.  This seems to happen each time the service deployment is updated.

**Comment by livebe01** [comment] 2023-10-12 13:19
Thanks @AlexThurston. We saw this on our end as well and are working on it.

**Comment by livebe01** [comment] 2023-10-12 13:28
We think this specific instance of this issue is tied to some older hardware we're running on... should be mitigated by our pending/upcoming Prod migration.
