### ISSUE TITLE
AES-CTR: payload length not observed by server

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/ACVP-Server#70] opened 2021-01-21 13:36 UTC
**environment**
Demo

**testSessionId**
138695

**vsId**
435066

**Algorithm registration**
```
      {
        "revision":"1.0",
        "algorithm":"ACVP-AES-CTR",
        "direction":[
          "encrypt",
          "decrypt"
        ],
        "keyLen":[
          128,
          192,
          256
        ],
        "payloadLen":[
          {
            "min":8,
            "max":128,
            "increment":8
          }
        ],
        "ivLen":[
          128
        ],
        "ctrSource":"external",
        "overflowCounter":false,
        "incrementalCounter":true
      },
```

The payload length shall be multiple of bytes.

The test vector, however, contains:

```
          {
            "tcId": 146,
            "pt": "CED180",
            "payloadLen": 21,
            "iv": "AE23C78545B4D36E4E04540FFD6EB818",
            "key": "E6375DE96A64DD47CC665068B20D80B9322AEDBAD2991BFE"
          },
          {
            "tcId": 147,
            "pt": "6BEEA0",
            "payloadLen": 21,
            "iv": "A33B96357BCCA1614610DFC21FF791F1",
            "key": "B9427D8AB52FC7D1FBDF9387EAA9B6F0CFCC352DD85D3966"
          },
```

**Comment by Kritner** [comment] 2021-01-21 13:58
At a glance this looks to be a duplicate of https://github.com/usnistgov/ACVP-Server/issues/66
I'll be getting a fix out for it once internal testing finishes.

**Comment by smuellerDD** [comment] 2021-01-21 14:06
Am Donnerstag, dem 21.01.2021 um 05:59 -0800 schrieb Russ Hammett:
> At a glance this looks to be a duplicate of
> https://github.com/usnistgov/ACVP-Server/issues/66
> I'll be getting a fix out for it once internal testing finishes.
> 

Agreed.

**Comment by Kritner** [comment] 2021-02-03 18:30
Closing this as duplicate of #66

**Closed by Kritner** 2021-02-03 18:30 UTC
