### ISSUE TITLE
HTTP timeouts receiving headers

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP-Server#61] opened 2021-01-07 17:51 UTC
**environment**
Demo/Prod

**Endpoint in which the error is experienced**
Vendor, requests, etc...

When trying to perform an action on demo or prod I seem to be getting HTTP timeouts where I'm not even getting header information before the client's configured timeout (30 seconds).  This was happening once in a while earlier in the day, but seems to be happening A LOT more often currently.

```
acvp-cli: error: Get "https://acvts.nist.gov/acvp/v1/vendors?limit=20&offset=0": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by AlexThurston** [comment] 2021-01-07 17:58
Hmm.  Seems to not be a problem any more.

**Comment by AlexThurston** [comment] 2021-01-07 19:39
I may have spoke too soon.  It's still something that is happening.

**Comment by AlexThurston** [comment] 2021-01-07 19:47
```(dev) macbook :: Code/goacvp/v2 ‹master*› % date; time acvp-cli vendor list                                                                                                   
Thu  7 Jan 2021 14:40:20 EST
acvp-cli: error: Get "https://demo.acvts.nist.gov/acvp/v1/vendors?limit=20&offset=0": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
acvp-cli vendor list  0.44s user 0.08s system 1% cpu 30.961 total
```

**Comment by Kritner** [comment] 2021-04-28 12:16
@AlexThurston sorry must have missed this come in. I suppose it would have had to have been something transient around that time.  I'm assuming the issue is not currently present, so closing for now.

**Closed by Kritner** 2021-04-28 12:16 UTC
