### ISSUE TITLE
Problem in TLS-v1.2 RFC7627 request generation

### ISSUE THREAD

**Issue by YasuhikoK** [usnistgov/ACVP-Server#139] opened 2021-09-06 08:29 UTC
**environment**
Demo

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
[
    {
        "acvVersion": "1.0"
    },
    {
        "algorithms": [
            {
                "algorithm": "TLS-v1.2",
                "mode": "KDF",
                "revision": "RFC7627",
                "hashAlg":[ "SHA2-256" ]
            }
        ]
    }
]

This definition worked without error in May 2021.

**Endpoint in which the error is experienced**
N/A

**Expected behavior**
request is generated.

**Additional context**
We got 400 error received from ACVT Demo server and error messages are as following.

***ACVP [ERR][log_network_status:1247]--> 400 error received from server. Message:
***ACVP [ERR][log_network_status:1248]--> [
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "TLS-v1.2-KDF-RFC7627: No Hash Algs supplied."
    ]
  }
]

Could you help us to avoid this situation ?

**Comment by livebe01** [comment] 2021-09-13 14:49
Hi @YasuhikoK and @smuellerDD, I wanted to let you know that we've replicated the issue you're experiencing on our end and are working on a fix. It looks like the issue, i.e., "No Hash Algs supplied" error when hashAlg is supplied, was introduced in [v1.1.0.19](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.19).

**Comment by Kritner** [comment] 2021-09-22 13:51
This change is on demo in release [v1.1.0.21](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.21)

**Comment by abkarcher** [comment] 2021-09-22 14:00
Hello,

I still seem to be experiencing this error, unless I am doing something incorrectly. Registration:
```
[{"acvVersion":"1.0"},{"algorithms":[{"algorithm":"TLS-v1.2","revision":"RFC7627","mode":"KDF","hashAlg":["SHA2-256","SHA2-384","SHA2-512"],"prereqVals":[{"algorithm":"SHA","valValue":"same"},{"algorithm":"HMAC","valValue":"same"}]}]}]
```
Response:
```
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "TLS-v1.2-KDF-RFC7627: No Hash Algs supplied."
    ]
  }
```
Thanks,
Andrew

**Comment by livebe01** [comment] 2021-09-22 15:46
Not sure what's going on there. We'll take a look.

**Comment by smuellerDD** [comment] 2021-09-22 16:37
Works now.

**Comment by abkarcher** [comment] 2021-09-22 16:39
Yep, confirmed it is working for me now. Thank you!

**Comment by livebe01** [comment] 2021-09-22 16:58
Perfect, thanks All! Closing out this ticket now

**Closed by livebe01** 2021-09-22 16:58 UTC
Labels: bug
