### ISSUE TITLE
TestSessions Get Issue

### ISSUE THREAD

**Issue by asant57** [usnistgov/ACVP-Server#89] opened 2021-03-15 12:36 UTC
**environment**
Demo

**testSessionId**
Null

**vsId**
Null

**Algorithm registration**
Null

**Endpoint in which the error is experienced**
https://[acvpUrl]/acvp/v1/testSessions GET

**Observed behavior**
I believe that the server is returning a 200 (OK) status and nothing in the results.

**Expected behavior**
A paginated view of all the user's current testSessions or an exception for what is incorrect.

**Additional context**
Partial client logs (Overview Attempt to Access TestSessions, see that the AccessToken is null then login to get the generic AccessToken, Send the request): 
[3/15/2021 8:28:19 AM] [INFO] [GetDataAsync] Sending the [testSessions] GET request to the server [https://demo.acvts.nist.gov:443]
[3/15/2021 8:28:19 AM] [DEBUG] [GetDataAsync] Sending to the URI: [https://demo.acvts.nist.gov:443/acvp/v1/testSessions]
[3/15/2021 8:28:19 AM] [WARNING] [GetDataAsync] The Access token required to access this page is currently [NULL], attempting to log in to access the page.
[3/15/2021 8:28:19 AM] [INFO] [LoginAsync] Start Login Sequence
[3/15/2021 8:28:19 AM] [INFO] [PostDataAsync] Sending the [login] POST request to the server [https://demo.acvts.nist.gov:443]
[3/15/2021 8:28:19 AM] [DEBUG] [PostDataAsync] Sending to the URI: [https://demo.acvts.nist.gov:443/acvp/v1/login]
[3/15/2021 8:28:20 AM] [INFO] [LoginAsync] Finished Login Sequence.
[3/15/2021 8:28:20 AM] [INFO] [GetDataAsync] Completed Login attempt actions.
[3/15/2021 8:28:20 AM] [DEBUG] [GetDataAsync] Send of GET request
[3/15/2021 8:29:23 AM] [DEBUG] [GetDataAsync] Result of GET request received
[3/15/2021 8:29:23 AM] [DEBUG] [GetDataAsync] The server returned the status code [200] - [OK] 
[3/15/2021 8:29:23 AM] [INFO] [GetDataAsync] The server returned a successful response. Attempting to parse the returned object.
[3/15/2021 8:29:23 AM] [DEBUG] [GetDataAsync] The server returned the object []

**Comment by Kritner** [comment] 2021-03-16 15:38
A change has been pushed to demo in [hotfix v1.1.0.16-1](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.16-1) that I *believe* solves this problem. There was an issue in how we were aggregating the data for this endpoint that caused it take take entirely too long, and I believe you were hitting a timeout of sorts.

Execution time of this query for my user in demo went from 15 seconds, to ~50ms.  Please let me know if the issue is solved from your perspective or not.

**Comment by asant57** [comment] 2021-03-16 17:46
Demo Currently appears to be handling this better. I am now able to get a paginated response back from the server instead of the previous behavior

**Comment by Kritner** [comment] 2021-03-17 19:10
The fix for this is on prod in [hotfix v1.1.0.16-1](https://github.com/usnistgov/ACVP-Server/releases/tag/v1.1.0.16-1)

**Closed by Kritner** 2021-03-17 19:10 UTC

**Comment by mmccarl** [comment] 2021-03-18 15:55
Aaron,here are the RSA_Engine demo vectors you requestedMichael McCarl | ÆGISOLVE, INC. | Senior Software Developer | tel: 650.386.1436 | fax: 650.386.1495 |415 Fairchild Dr. | Mountain View, CA. 94043 | aegisolve.comFollow ÆGISOLVE, INC. on LinkedIn: linkedin.com/company/aegisolve----------------------Confidentiality Notice-----------------------------This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.--------------------------------------------------------------------------- 


-------- Original Message --------
Subject: Re: [usnistgov/ACVP-Server] TestSessions Get Issue (#89)
From: Russ Hammett ***@***.***>
Date: Wed, March 17, 2021 3:10 pm
To: usnistgov/ACVP-Server ***@***.***>
Cc: Subscribed ***@***.***>

 Closed #89. —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
